VotingPlatform/deeva/deeva/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include('experiments.urls_admin', namespace="experiments_admin")),
    url(r'^admin/', admin.site.urls),
    url(r'^impressum/', TemplateView.as_view(template_name="impressum.html"), name="impressum"),
    url(r'^news/', include('news.urls')),
    url(r'^', include('experiments.urls', namespace="experiments")),
]

VotingPlatform/deeva/experiments/urls.py
from django.conf.urls import url

from . import views, views_admin

app_name = 'experiments'

urlpatterns = [
    url(r'^experiments/all', views.allExperiments, name='allExperiments'),
    url(r'^experiments/(?P<wizard_id>[0-9]+)$', views.oneExperiment, name='oneExperiment'),

    url(r'^wiz/(?P<wizard_id>[0-9]+)/vote$', views.vote, name='vote'),
    url(r'^wiz/(?P<wizard_id>[0-9]+)/vote_after_break_$', views.vote, {'had_break': True}, name='vote_after_break'),

    
    url(r'^wiz/(?P<wizard_id>[0-9]+)/break$', views.wizard_break, name='wizard_break'),
    
    url(r'^wiz/(?P<wizard_id>[0-9]+)/comp_vote$', views.comp_vote, name='comp_vote'),
    url(r'^wiz/(?P<wizard_id>[0-9]+)/rate_vote$', views.rate_vote, name='rate_vote'),


    url(r'wiz/(?P<wizard_id>\w+)/end', views.wizard_exit, name='wizard_exit'),
    url(r'wiz/(?P<wizard_id>\w+)/infos', views.wizard_personalinfos, name='wizard_personalinfos'),
    # url(r'wiz/(?P<wizard_id>\w+)/vote', views.wizard_vote, name='wizard_vote'),
    url(r'wiz/(?P<wizard_id>\w+)/example', views.wizard_example, name='wizard_example'),
    url(r'wiz/(?P<wizard_id>\w+)/disclaimer', views.wizard_disclaimer,
        name='wizard_disclaimer'),
    url(r'wiz/(?P<wizard_id>\w+)/welcome', views.wizard_welcome, name='wizard_welcome'),
    url(r'wiz/(?P<wizard_id>\w+)/checkuser', views.wizard_checkuser, name='wizard_checkuser'),
    url(r'wiz/(?P<wizard_id>\w+)', views.wizard_start, name='wizard_start'),

    url(r'^individuals/content/(?P<individual_id>[0-9]+)/(?P<content_name>[\w.]+)$', views.send_individual_content, name='send_individual_content'),

    url(r'^$', views.index, name='index'),
]

VotingPlatform/deeva/news/urls.py
from django.conf.urls import url

from . import views

app_name = 'news'

urlpatterns = [
	url(r'^$', views.allNews, name='allNews'),
    url(r'^(?P<news_id>[0-9]+)$', views.oneNews, name='oneNews'),
]

VotingPlatform/deeva/experiments/forms.py
from django import forms
from django.forms import ModelForm
from .models import Individual


class TestForm(forms.Form):
    CHOICES = (('1', 'First',), ('2', "I don't know",), ('3', 'Second',))
    #from .buttonradioselect import ButtonRadioSelect
    
    test_field = forms.ChoiceField(choices = CHOICES, widget = forms.RadioSelect, label = "text")
    choice_field1 = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
            
    choice_field2 = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    choice_field3 = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)


class CompareForm(forms.Form):
    CHOICES = (('1', 'First',), ('2', "I don't know",), ('3', 'Second',))
    #from .buttonradioselect import ButtonRadioSelect
    
    test_field = forms.ChoiceField(choices = CHOICES, widget = forms.RadioSelect, label = "text")
    choice_field1 = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
            
    choice_field2 = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    choice_field3 = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)

VotingPlatform/deeva/experiments/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.http import JsonResponse
from django.contrib import messages
from django.forms import modelformset_factory
from deeva.settings import *

from .models import VotingWizard, CompareVote, RateVote
from .functions import *
from questions.models import Answer
from django.contrib.auth.models import User

from sendfile import sendfile

from questions.countries import COUNTRIES

# Create your views here.

def index(request):
    """return the index/home/welcome page"""
    from news.functions import getNews
    newss = getNews(limit=3, short=True)
    return render(request, 'experiments/welcome.html', {'newss':newss})

def allExperiments(request):
    """return all experiments (for the user, in reality wizards) on one page"""
    from .models import VotingWizard
    wizards = VotingWizard.objects.all()
    return render(request, 'experiments/allexperiments.html', {'wizards':wizards})

def oneExperiment(request, wizard_id):
    """return one specific experiment view"""
    from .models import VotingWizard
    from .functions import getOneWizard
    try:
        wizard = getOneWizard(wizard_id)
    except VotingWizard.DoesNotExist as e:
        from django.contrib import messages
        messages.error(request, "Sorry. The requested experiment was not found.")
        return allExperiments(request)
    
    return render(request, 'experiments/oneexperiment.html', {'wizard':wizard})

def wizard_start(request, wizard_id):
    return wizard_welcome(request, wizard_id)


def wizard_checkuser(request, wizard_id):
    if request.method == 'POST':
        print('a')
        if request.POST.get("flush_button")=="flush_button":
            print('b')
            request.session.flush()
            return HttpResponseRedirect("")

    #check if wizard exists
    try:
        wizard = VotingWizard.objects.get(pk=wizard_id)
    except VotingWizard.DoesNotExist:
        messages.error(request, 'The requested experiment does not exist. You were redirected to the homepage.')
        return redirect('experiments:index') 

    #check that user is not logged in
    if not request.user.is_authenticated:

        #check, if the user has session_keys or create them
        if hasattr(request, 'session') and not request.session.session_key:
            session_id_created = True
            request.session.save()
            request.session.modified = True
        else:
            session_id_created = False

        session_id = request.session.session_key
        #check, if the user already exists in the db and create a new one if needed
        users = User.objects.filter(username=session_id)
        if users:
            user = users[0]
        else:
            user = User.objects.create_user(username=session_id, password=None, email=None)
            user.save()

        #check number of votes for this wizard and generation
        dependent_variables = wizard.generation.experiment.dependent_variables.attributes.all().count()
        rate_votes = RateVote.objects.filter(generation=wizard.generation, wizard=wizard, user=user).count()/dependent_variables
        comp_votes = CompareVote.objects.filter(generation=wizard.generation, wizard=wizard, user=user).count()/dependent_variables



    else:
        session_id_created = None
        user = request.user
        rate_votes = 0
        comp_votes = 0


    template = 'experiments/wizard_checkuser.html'

    context = {
        'wizard':wizard,
        'session_id_created': session_id_created,
        'vote_user': user,
        'rate_votes': rate_votes,
        'comp_votes': comp_votes,

    }

    return render(request, template, context)
    

def wizard_welcome(request, wizard_id):
    from django.template import Context, Template, loader
    #check if wizard exists
    try:
        wizard = VotingWizard.objects.get(pk=wizard_id)
    except VotingWizard.DoesNotExist:
        messages.error(request, 'The requested experiment does not exist. You were redirected to the homepage.')
        return redirect('experiments:index') 

    #check that user is not logged in
    if request.user.is_authenticated: 
        messages.error(request, "(VE01) The current user is logged in and was not eligible to vote and therefore was redirected to this page.")
        return redirect('experiments:wizard_checkuser', wizard_id=wizard.id)

    #check, if user has a valid session
    if hasattr(request, 'session') and not request.session.session_key:
        messages.error(request, "(VE02) This user didn't have a valid session and was not eligible to vote and therefore was redirected to this page.")
        return redirect('experiments:wizard_checkuser', wizard_id=wizard.id)

    session_id = request.session.session_key
    
    #check, if the user exists in the db
    users = User.objects.filter(username=session_id)
    if users:
        vote_user = users[0]
    else:
        messages.error(request, "(VE03) This session didn't have a valid user account and therefore was redirected to this page.") 
        return redirect('experiments:wizard_checkuser', wizard_id=wizard.id)

    #check number of votes for this wizard and generation
    dependent_variables = wizard.generation.experiment.dependent_variables.attributes.all().count()
    rate_votes = RateVote.objects.filter(generation=wizard.generation, wizard=wizard, user=vote_user).count()/dependent_variables
    comp_votes = CompareVote.objects.filter(generation=wizard.generation, wizard=wizard, user=vote_user).count()/dependent_variables

    if rate_votes > 0 or comp_votes > 0:
        messages.info(request, "(VE10) This user already has votes and therefore was redirected to this page. Please check on how to continue.")
        return redirect('experiments:wizard_checkuser', wizard_id=wizard.id)


    mode = request.session.get('wizard_mode', 'error')

    #check if any mode is enabled
    if not wizard.enable_rating_mode and not wizard.enable_compare_mode:
        messages.error(request, "This experiment is currently disabled. You will not be able to complete this experiment! Sorry for the inconvenience caused.")


    #write context
    context = {'wizard': wizard, 'currentpage': 1, 'totalpages': wizard.number_of_votes + 5}

    #check if alternative website is present
    if wizard.welcome_html == "":
        template = loader.get_template('experiments/wizard_welcome.html')
    else:
        template = Template(wizard.welcome_html)
        context = Context(context)
    
    #return page
    return HttpResponse(template.render(context))

def wizard_disclaimer(request, wizard_id):
    from django.template import Context, Template, loader
    #check if wizard exists
    try:
        wizard = VotingWizard.objects.get(pk=wizard_id)
    except VotingWizard.DoesNotExist:
        messages.error(request, 'The requested experiment does not exist. You were redirected to the homepage.')
        return redirect('experiments:index')

    #check if any mode is enabled
    if not wizard.enable_rating_mode and not wizard.enable_compare_mode:
        messages.error(request, "This experiment is currently disabled. You will not be able to complete this experiment! Sorry for the inconvenience caused.")  

    #write context
    context = {'wizard': wizard, 'currentpage': 2, 'totalpages': wizard.number_of_votes + 5}

    #check if alternative website is present
    if wizard.disclaimer_html == "":
        template = loader.get_template('experiments/wizard_disclaimer.html')
    else:
        template = Template(wizard.disclaimer_html)
        context = Context(context)
    
    #return page
    return HttpResponse(template.render(context))

def wizard_example(request, wizard_id):
    from django.template import Context, Template, loader
    #check if wizard exists
    try:
        wizard = VotingWizard.objects.get(pk=wizard_id)
    except VotingWizard.DoesNotExist:
        messages.error(request, 'The requested experiment does not exist. You were redirected to the homepage.')
        return redirect('experiments:index')


    #get session key and create an anonymous user
    user = request.user

    session_id = request.session._get_or_create_session_key()
    #anonuser, created = AnonymousUser.objects.get_or_create(session_id=session_id)

    #check available modes and roll dice to see which mode is presented to the user
    if wizard.enable_rating_mode and wizard.enable_compare_mode:
        from random import randint
        if randint(0,1) == 0:
            request.session['wizard_mode'] = 'rate'
        else:
            request.session['wizard_mode'] = 'comp'

    if wizard.enable_rating_mode:
        request.session['wizard_mode'] = 'rate'

    elif wizard.enable_compare_mode:
        request.session['wizard_mode'] = 'comp'

    else:
        messages.error(request, "This experiment is currently disabled. You will not be able to complete this experiment! Sorry for the inconvenience caused.")
        request.session['wizard_mode'] = 'error'

    #reset vote counter and voted ids
    #request.session['wizard_counter'] = 0
    #request.session['wizard_vote_ids'] = ""

    #write context
    context = {'mode': request.session.get('wizard_mode', 'error'), 'wizard': wizard, 'currentpage': 3, 'totalpages': wizard.number_of_votes + 5}

    #check if alternative website is present
    if wizard.example_html == "":
        template = loader.get_template('experiments/wizard_example.html')
    else:
        template = Template(wizard.example_html)
        context = Context(context)
    
    #return page
    return HttpResponse(template.render(context))

def wizard_break(request, wizard_id):
    from django.template import Context, Template, loader
    #check if wizard exists
    try:
        wizard = VotingWizard.objects.get(pk=wizard_id)
    except VotingWizard.DoesNotExist:

VotingPlatform/deeva/experiments/templates/experiments/comp_vote.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}


	<h1>Which individual looks...</h1>

	

	<div class="row">
		<!-- left individual L: {{individual1.id}}-->
		<div id="cf1" class="content-frame" style="margin-left: auto;" col-sm-6 col-md-4 text-center order-xs-1 order-md-1>
		
			<div class="img-thumbnail">
				{% for content_name in wizard.generation.experiment.content_list %}
					<img class="img-responsive img-vote" style="width:{{wizard.size_of_comp_content}}; max-height:{{wizard.size_of_comp_content}};" src="{% url 'experiments:send_individual_content' individual1.id content_name %}">
				{% endfor %}
			</div>
		</div>


		

		<!-- comparison vote panel -->


		

			
		<div id="ff" class="form-frame" style="margin: auto;" col-sm-12 col-md-4 text-center order-xs-3 order-md-2>

			<form id=fake-form>
				{% for v in dependent_variables %}
				<div class="form-group">
					<label for="">...more {{v.name}}?</label><br>
					<div class="btn-group btn-group-toggle" data-toggle="buttons" data-variable="{{v.id}}">
						<label class="btn btn-secondary">
							<input type="radio" name="var{{v.id}}" data-vote="-1" autocomplete="off"> First
						</label>
						<label class="btn btn-secondary">
							<input type="radio" name="var{{v.id}}" data-vote="0" autocomplete="off"> I don't know
						</label>
						<label class="btn btn-secondary">
							<input type="radio" name="var{{v.id}}" data-vote="1" autocomplete="off"> Second
						</label>
					</div>
				</div>
				{% endfor %}
			</form>




			{% block buttons %}
			<div class="text-center mt-5">
				<button id="fake-send-btn-click" type="button" class="btn btn-primary">
					<span class="fa fa-chevron-right"></span> {% block button_cnt %}Save &amp; Continue{% endblock %}
				</button>
				<button id="fake-send-btn-spinner" type="button" class="btn btn-warning disabled d-none">
					<span class="fa fa-pulse fa-spinner"></span> {% block button_save %}Saving...{% endblock %}
				</button>
				<button id="fake-send-btn-finished" type="button" class="btn btn-success disabled d-none">
					<span class="fa fa-check"></span> {% block button_load %}Saved! Loading next page...{% endblock %}
				</button>
			</div>
			{% endblock %}
			
		</div>


		<!-- right individual R: {{individual2.id}} -->
		<div id="cf2" class="content-frame" style="margin-right: auto; margin-bottom: 10px;" col-sm-6 col-md-4 text-center order-xs-2 order-md-3>
		
			<div class="img-thumbnail">
				{% for content_name in wizard.generation.experiment.content_list %}
					<img class="img-responsive img-vote" style="width:{{wizard.size_of_comp_content}}; max-height:{{wizard.size_of_comp_content}};" src="{% url 'experiments:send_individual_content' individual2.id content_name %}">
				{% endfor %}
			</div>
		</div>

		

		
		
	</div>

	<div class="row">
		<div id="after-content" class="" style=""></div>
	</div>

	


	<form action="" method="post" autocomplete="off" id="real-form" hidden>
	    {% csrf_token %}
	    {{ formset.as_p }}
	    <input type="submit" value="Submit" />
	</form>
	

         
{% endblock %}



{% block scripts %}
<script>
	$("#fake-form")[0].reset(); //reset fake form on page load

	$("#fake-form").change(function() {
		//get total number of variables to fill and iterate through them
		var total_forms = $('input[name=form-TOTAL_FORMS]').val();


		for (i = 0; i < total_forms; i++) {

			//get variable id for current form
			vid = $('#id_form-'+i+'-variable').val();
			console.log(vid)

			//get selected vote from the fake form
			var vote = $('input[name=var'+vid+']:checked', '#fake-form').data('vote');

			//paste value in real form
			$('#id_form-'+i+'-vote').val(vote);
		} ;

	});


	$("#fake-send-btn-click").click(function() {
			var form = $("#real-form");
		    var url = form.attr('action');

		    $('#fake-send-btn-click').addClass("d-none");
		    $('#fake-send-btn-spinner').removeClass("d-none");

		    $.ajax({
		           type: "POST",
		           url: url,
		           data: form.serialize(),
		        }).done(function(data){
		        	if(data.success){
		        		//proceed
		        		$('#fake-send-btn-spinner').addClass("d-none");
		    			$('#fake-send-btn-finished').removeClass("d-none");
		    			window.location.href = "{% url 'experiments:vote' wizard.id %}";
		        	} else {
		        		//re-do form
		        		$('#fake-send-btn-spinner').addClass("d-none");
		    			$('#fake-send-btn-click').removeClass("d-none");
		    			alert("Please fill out the form before clicking on continue.");
		        	}
		        	
		        }).fail(function(jqXHR, textStatus, errorThrown){
		        	$('#fake-send-btn-spinner').addClass("d-none");
		    		$('#fake-send-btn-click').removeClass("d-none");
		        	alert(textStatus);
		        })
		});


	//
	// Some dirty stuff.
	// The defaukt main container has too big borders.
	// If we are using this header-less version, then we set the main class to be "fluid",
	// and the side borders will be significantly shrunk.
	$(document).ready(function () {
	    // alert("Class substitution")
		$("#main-content").removeClass("container").addClass("container-fluid");
	});


	function move_form() { 
		//check whether the content frames are on the same height
		//if not, move form to the bottom
		// alert("move_form start")
		if ($("#cf1").position().top != $("#cf2").position().top){
			$("#ff").insertAfter($("#after-content"));

			//check whether their still not on the same height
			//if not, center them
			if ($("#cf1").position().top != $("#cf2").position().top){
				$(".content-frame").css("margin-left", "auto");
				$(".content-frame").css("margin-right", "auto");
			};
		};
	};

	$(document).ready(move_form); 
	$(window).resize(move_form);


</script>
{% endblock %}	

VotingPlatform/deeva/experiments/templates/experiments/experimentpanels.html
{% for wizard in wizards %}
	<div class="card mb-3">
	  	<div class="card-header">
	    	<a href="{% url 'experiments:oneExperiment' wizard.id %}"> {{wizard.name}} </a>
	    	<div class="pull-right">
			    &nbsp;</span> {{wizard.created}}
			</div>
	    	<div class="pull-right">

			    	<a href="https://www.facebook.com/sharer/sharer.php?u=BASEURLTODO{{experiment.url}}" target="_blank" class="btn btn-sm btn-social btn-facebook">
				    	<span class="fa fa-facebook"></span>Share
				  	</a> 
					<a href="https://twitter.com/intent/tweet?url=www.google.de&text={{experiment.name}} BASEURLTODO{{news.url}}&via=Deeva_mmci" target="_blank" class="btn btn-spacing btn-sm btn-social btn-twitter">
				    	<span class="fa fa-twitter"></span>Tweet
			    	</a> 

			    	{% if user.is_superuser %}
				    	<div class="btn-group" role="group" aria-label="Settings">
						 	<a href="{% url 'admin:experiments_votingwizard_change' wizard.id %}" class="btn btn-outline-dark btn-sm">
					    		<span class="fa fa-cog"></span> Wizard
				    		</a> 
						 	<a href="{% url 'admin:experiments_generation_change' wizard.generation.id %}" class="btn btn-outline-dark btn-sm">
						 		Generation
				    		</a>
						 	<a href="{% url 'admin:experiments_experiment_change' wizard.generation.experiment.id %}" class="btn btn-outline-dark btn-sm">
					    		Experiment
				    		</a>
						</div>
					{% endif %}

			    </div>
		    <div class="clearfix"></div>
		</div>
		<div class="card-body">
			<div class="row">
				<!-- experiment description-->
				<div class="col-md-8">
					<p> {{wizard.generation.experiment.description|safe}} </p>
				</div>
				<!-- information and buttons-->
				<div class="col-md-4">
				
					<div class="btn-group btn-block ">
						<a class="btn btn btn-block btn-primary " href="{% url 'experiments:wizard_start' wizard.id %}" role="button">
							<span class="fa fa-pencil"></span> Vote
						</a>
					</div>
				
					<div class="btn-group btn-block">
						<a class="btn btn btn-block btn-light disabled" href="TODO" role="button">
							<span class="fa fa-search"></span> Search
						</a>
					</div>

					<div class="btn-group btn-block">
						<a class="btn btn-link btn-block" href="TODO" role="button">
							<span class="fa fa-info-o"></span></span> More information &amp; Statistics &raquo;
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endfor %}

VotingPlatform/deeva/experiments/templates/experiments/rate_vote.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load staticfiles %}
{% load experiments_extra %}


{% block content %}

	{% block titletext %}
		<h3>Please vote on the following...</h3>
	{% endblock %}

	{% block text %}
		<p>Select an option in each row and click on the button to continue.</p>
	{% endblock %}


	{% block progress %}
		<!-- Progress: {{current_vote}} of {{wizard.number_of_votes}} -->
		<!--div class="progress">
		  <div class="progress-bar" role="progressbar" style="width: {{percentage}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">{{percentage}}%</div>
		</div-->
		{% block progress-text %}
		<p class="mb-0 text-center">
				{% block progress-percentage %}{{percentage}}%{% endblock %}
				{% block progress-item %}{{current_vote}}/{{total_votes}}{% endblock %}
		</p>
		{% endblock %}

		{% block progress-bar %}
		<div class="progress">
        {% for b in progressbars %}
          {% if b.color == 'danger' %}
            <div class="text-center" role="progressbar" style="width: {{b.size|mult:100}}%" ></div>
          {% else %}
            <div class="progress-bar bg-{{b.color}}" role="progressbar" style="width: {{b.size|mult:100}}%" ></div>
          {% endif %}
        {% endfor %}
      	</div>
      	{% endblock %}

	{% endblock %}
	
	<!-- individual content -->
	{% block ind_content %}
		<div class="row m-3">
			<div class="mx-auto d-block">
			{% for content_name in wizard.generation.experiment.content_list %}
			<img class="" style="width:{{wizard.size_of_content}}; max-height:{{wizard.size_of_content}};" src="{% url 'experiments:send_individual_content' individual.id content_name %}" alt="{{content_name}} of individual #{{individual.id}}">
			
			{% endfor %}
			</div>
		</div>
	{% endblock %}

	<!-- fake form for the user -->
	{% block fake_form %}
		<div class="text-center">
			<form id="fake-form" class="">
				
				{% for vg in dependent_variables_table %}
				<table class="table table-striped text-center" style="font-size:12pt;padding:5pt;">
					<thead>
					<tr>
						<th></th>
						{% for label in vg.header %}
						<th>{{label}}</th>
						{% endfor %}
						<th></th>
					</tr>
					</thead>
					<tbody>
						{% for vr in vg.vrs %}
						<tr>
							<td>{{vr.variable.left}}</td>
							{% for label in vg.header %}
							<td style="align: middle; padding: 0.4rem;">
								<label style="padding: 5pt; margin: 0;">
									<input type="radio" data-variable-id="{{vr.variable.id}}" data-label="{{label}}" id='{{vr.variable.id}}-{{label}}' name="var{{vr.variable.id}}" style="width: 1em; height: 1em;">
								</label>
							</td>
							{% endfor %}
							<td>{{vr.variable.right}}</td>
						</tr>
						{% endfor %}
					</tbody>
					
				</table>
				{% endfor %}

			</form>

	
			
		{% block buttons %}
			<button id="fake-send-btn-click" type="button" class="btn btn-primary">
				<span class="fa fa-chevron-right"></span> {% block button_cnt %}Save &amp; Continue{% endblock %} 
			</button>
			<button id="fake-send-btn-spinner" type="button" class="btn btn-warning disabled d-none">
				<span class="fa fa-pulse fa-spinner"></span> {% block button_save %}Saving...{% endblock %} 
			</button>
			<button id="fake-send-btn-finished" type="button" class="btn btn-success disabled d-none">
				<span class="fa fa-check"></span> {% block button_load %}Saved! Loading next page...{% endblock %} 
			</button>
		{% endblock %}

		</div>
	{% endblock %}

	<!-- real form to submit -->
	{% block real_form %}
		<div class="d-none">
			<form action="" method="post" autocomplete="off" id="real-form">
			    {% csrf_token %}
			    {{ formset.as_p }}
			    <input type="submit" value="Submit" />
			</form>
		</div>
	{% endblock %}
	

         
{% endblock %}



{% block scripts %}
	<script>
		$("#fake-form")[0].reset(); //reset fake form on page load

		$("#fake-form").change(function() {
			//get total number of variables to fill and iterate through them
			var total_forms = $('input[name=form-TOTAL_FORMS]').val();

			for (i = 0; i < total_forms; i++) {

				//get variable id for current form
				vid = $('#id_form-'+i+'-variable').val();

				//get selected label from the fake form
				var label = $('input[name=var'+vid+']:checked', '#fake-form').data('label');
				
				//paste value in real form
				$('#id_form-'+i+'-text_value').val(label);
			} ;

		});


		$("#fake-send-btn-click").click(function() {
			var form = $("#real-form");
		    var url = form.attr('action');

		    $('#fake-send-btn-click').addClass("d-none");
		    $('#fake-send-btn-spinner').removeClass("d-none");

		    $.ajax({
		           type: "POST",
		           url: url,
		           data: form.serialize(),
		        }).done(function(data){
		        	if(data.success){
		        		//proceed
		        		$('#fake-send-btn-spinner').addClass("d-none");
		    			$('#fake-send-btn-finished').removeClass("d-none");
		    			window.location.href = "{% url 'experiments:vote' wizard.id %}";
		        	} else {
		        		//re-do form
		        		$('#fake-send-btn-spinner').addClass("d-none");
		    			$('#fake-send-btn-click').removeClass("d-none");
		    			alert("Please fill out the form before clicking on continue.");
		        	}
		        	
		        }).fail(function(jqXHR, textStatus, errorThrown){
		        	$('#fake-send-btn-spinner').addClass("d-none");
		    		$('#fake-send-btn-click').removeClass("d-none");
		        	alert(textStatus);
		        })
		});



		


	</script>
{% endblock %}	

VotingPlatform/deeva/experiments/templates/experiments/wizard_break.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}
	{% load staticfiles %}

	{% block titletext %}
		<h3>Short break</h3>
	{% endblock %}
	
	{% block text %}
		<p>Please take a short break before proceeding.</p>

		<p>Click on the button to continue.</p>
	{% endblock %}

	{% block input %}
		<p>
			<a id="withjsbtn" class="btn btn-primary" href="{% url 'experiments:vote_after_break' wizard.id %}">
				<span class="fa fa-chevron-right"></span> {% block button_text %}Continue{% endblock %}
			</a>
		
		</p>

	{% endblock %}


{% endblock %}