VotingPlatform/deeva/deeva/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include('experiments.urls_admin', namespace="experiments_admin")),
    url(r'^admin/', admin.site.urls),
    url(r'^impressum/', TemplateView.as_view(template_name="impressum.html"), name="impressum"),
    url(r'^news/', include('news.urls')),
    url(r'^', include('experiments.urls', namespace="experiments")),
]

VotingPlatform/deeva/experiments/urls.py
from django.conf.urls import url

from . import views, views_admin

app_name = 'experiments'

urlpatterns = [
    url(r'^experiments/all', views.allExperiments, name='allExperiments'),
    url(r'^experiments/(?P<wizard_id>[0-9]+)$', views.oneExperiment, name='oneExperiment'),

    url(r'^wiz/(?P<wizard_id>[0-9]+)/vote$', views.vote, name='vote'),
    url(r'^wiz/(?P<wizard_id>[0-9]+)/vote_after_break_$', views.vote, {'had_break': True}, name='vote_after_break'),

    
    url(r'^wiz/(?P<wizard_id>[0-9]+)/break$', views.wizard_break, name='wizard_break'),
    
    url(r'^wiz/(?P<wizard_id>[0-9]+)/comp_vote$', views.comp_vote, name='comp_vote'),
    url(r'^wiz/(?P<wizard_id>[0-9]+)/rate_vote$', views.rate_vote, name='rate_vote'),


    url(r'wiz/(?P<wizard_id>\w+)/end', views.wizard_exit, name='wizard_exit'),
    url(r'wiz/(?P<wizard_id>\w+)/infos', views.wizard_personalinfos, name='wizard_personalinfos'),
    # url(r'wiz/(?P<wizard_id>\w+)/vote', views.wizard_vote, name='wizard_vote'),
    url(r'wiz/(?P<wizard_id>\w+)/example', views.wizard_example, name='wizard_example'),
    url(r'wiz/(?P<wizard_id>\w+)/disclaimer', views.wizard_disclaimer,
        name='wizard_disclaimer'),
    url(r'wiz/(?P<wizard_id>\w+)/welcome', views.wizard_welcome, name='wizard_welcome'),
    url(r'wiz/(?P<wizard_id>\w+)/checkuser', views.wizard_checkuser, name='wizard_checkuser'),
    url(r'wiz/(?P<wizard_id>\w+)', views.wizard_start, name='wizard_start'),

    url(r'^individuals/content/(?P<individual_id>[0-9]+)/(?P<content_name>[\w.]+)$', views.send_individual_content, name='send_individual_content'),

    url(r'^$', views.index, name='index'),
]

VotingPlatform/deeva/news/urls.py
from django.conf.urls import url

from . import views

app_name = 'news'

urlpatterns = [
	url(r'^$', views.allNews, name='allNews'),
    url(r'^(?P<news_id>[0-9]+)$', views.oneNews, name='oneNews'),
]

VotingPlatform/deeva/deeva/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Deeva</title>

		<!-- Staticfiles -->
		{% load staticfiles %}

		<!-- Bootstrap Django & CSS -->
		{# Load the tag library for django-bootstrap3 #}
		{% load bootstrap3 %}


		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
		<link href="{% static "css/bootstrap-social.css" %}" rel="stylesheet">
	</head>

	<body>
		<!-- Top Navigation Bar -->
		{% block navbar %}
		{% if not wizard.distraction_free_mode %}


		<nav class="navbar navbar-expand-md navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="#">Deeva<small> a Depot of Evolving Avatars</small></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'experiments:index' %}">
								Home
							</a>
						</li>
						<!-- li class="nav-item">
							<a class="nav-link" href="{% url 'experiments:allExperiments' %}">
								Experiments
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">
								About
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">
								Documentation
							</a>
						</li -->
					</ul>
				</div>
			</div>
		</nav>
		{% endif %}
		{% endblock %}

		<!-- Main Content -->
		<div id="main-content" class="container mt-3">
		{% block messageblock %}		  
			  {% bootstrap_messages %}
		{% endblock %}
		{% block content %}		  
			  <h1>Empty Template</h1>
			  <p>The template didn't specify a content block or the base template was called directly. Add a content block to display something nice for the user :-)</p>
		{% endblock %}
		</div> <!-- /container -->

  		<!-- Footer after horizontal line -->
  		{% block footer %}
  		{% if not wizard.distraction_free_mode %}
  		<hr>
		<footer class="footer">
			<div class="container">
				<ul class="list-inline text-center text-muted">
					<li>DeEvA - Depot of Evolving Avatars &copy; 2013-{% now "Y" %}</li>
					<li><a href="http://slsi.dfki.de/" target="_blank">Sign Language Synthesis and Interaction group</a> at <a href="http://www.mmci.uni-saarland.de" target="_blank">MMCI</a> / <a href="http://www.dfki.de/web" target="_blank">DFKI</a></li>
					<li><a href="{% url 'impressum' %}">Site Credits</a> - <a href="https://imprint.mpi-klsb.mpg.de/mmci/deeva" target="_blank">Imprint</a> - <a href="https://data-protection.mpi-klsb.mpg.de/mmci/deeva" target="_blank">Data Protection</a></li>
				</ul>
			</div>
		</footer>
		{% endif %}
		{% endblock %}

		<!-- load scripts in the end jQuery and Bootstrap-->
		<script src='{% static "js/jquery.min.js" %}'></script>

		{# Load Bootstrap JavaScript #}    
		{% bootstrap_javascript %}

		{% block scripts %}
		{% endblock %}	

  	</body>
</html>

VotingPlatform/deeva/deeva/templates/impressum.html
{% extends "base.html" %}

{% block content %}

<h2>Site Credits</h2>

<h3>Legal Regulations:</h3>
<ul>
<li>section 5 State Agreement on Media Services</li>
<li>section 55 German Act on Teleservices</li>
</ul>
<h3>Publisher:</h3>
<ul><li>Fabrizio Nunnari, DFKI GmbH, Campus D3.2, Stuhlsatzenhausweg 3, D-66123 Saarbrücken, Deutschland</li>
<li>+49 (0) 681 302 3393</li>
<li>e-mail: deeva at mmci.uni-saarland.de</li></ul>
<h3>Legal Form:</h3>
<ul><li>Section 1 (1) Saarland University law</li>
<li>The university is a body governed by public law</li></ul>
<h3>Authorized Representative:</h3>
<ul><li>The university is legally represented by the president Prof. Dr. Volker Linneweber</li></ul>
<h3>Regulation Authority:</h3>
<ul><li>Saarland State Chancellery</li></ul>
<h3>(Turnover) Sales Tax ID No.:</h3>
<ul><li>DE138117521</li></ul>

<h3>Content liability:</h3>
<ul>
<li>The editors of the webpages make every effort to keep content accurate and up to date</li>
<li>Name of responsible person: Fabrizio Nunnari</li>
<!-- li> Design and Technical Platform <li -->
<li>Software: Apache, DJango</li>
</ul>
<h3>Liability Note / Disclaimer:</h3>
<ul>
<li>Information for questions on liability can be found in the Disclaimer</li>
<li>Despite careful content control we assume no liability fo the content of external links</li>
<li>For the corresponding content of linked pages, their administrators are responsible</li>
<li>We shall not assume any liability neither expressly nor implied for the type or correctness of the material offered</li>
<li>We shall not be liable for the material or use</li>
<li>In case contents of websites violate valid legal regulations, we kindly ask you to inform us immediately</li>
<li>We shall not assume any responsibility or guarantee for information following external links and shall not approve or support such information in terms of contents</li>
<li>We are only liable for our own contents under the general applicable laws</li>
<li>We did neither produce the contents of foreign websites and cannot influence on the contents of website of third parties</li>
<li>We are not liable for references and contributions by users in guest books, discussion forums and mailing lists</li>
</ul>
<h3>Copyright:</h3>
<ul>
<!-- li>copyright and further rights for texts, photographs, artwork lie within XX -->
<li>Further dissemination is allowed provided source is indicated (unless otherwise expressly stated)</li>
<li>Use for commercial purposes shall require approval</li>
<li>None of the materials may be copied, modified or used on other websites</li>
<li>Use is prohibited</li>
</ul>
<h3>Data Protection and IT Safety:</h3>
<ul>
<li>We shall be obliged to protect the private sphere of all persons using our site and to treat confidentially the personal data transmitted to us</li>
<li>The data shall be used exclusively for the purposes indicated and not disclosed to third parites</li>
<li>Your data will be deleted as soon as they will have served the purpose indicated</li>
<li>Possibly your web browser or client software transmits information via your computer to our servers through no fault of your own. Such information shall never be brought directly in connection with you but will only be evaluated in anonymous form</li>
</ul>

{% endblock %}